### SELECT Busca a informação do jogo
GET  http://localhost:3001/game/ HTTP/1.1

### SELECT Busca jogos usando o filtro de type
GET  http://localhost:3001/game?type=playstation HTTP/1.1

### INSERT Registra jogo (campos obrigatórios)
POST  http://localhost:3001/game HTTP/1.1
Content-Type: application/json

{
    "type": "playstation",
    "title": "God of War",
    "summary": "God of War é uma série de jogos eletrônicos de ação-aventura vagamente baseado nas mitologias grega e nórdica sendo criado originalmente por David Jaffe da Santa Monica Studio. Iniciada em 2005, a série tornou-se carro-chefe para a marca PlayStation, que consiste em oito jogos em várias plataformas.",
    "developer": "Santa Mônica",
    "genre": "RPG"
}

### UPDATE
PUT  http://localhost:3001/game/:game_id HTTP/1.1
Content-Type: application/json

{
    "developer": "CEGA",
    "genre": "Ação",
}

### DELETE Remove o jogo
DELETE  http://localhost:3001/game/:game_id HTTP/1.1