# Create image based on the official Node 10 image from the dockerhub
FROM node:10

# Create a directory where our app will be placed
RUN mkdir -p /backend

# Change directory so that our commands run inside this new directory
WORKDIR /backend

# Copy dependency definitions
COPY package*.json /backend/

# Install dependecies
RUN npm install

# Get all the code needed to run the app
COPY . /backend/

# Expose the port the app runs in
EXPOSE 3001

# Serve the app
CMD ["npm", "start"]